### ISSUE TITLE
Regarding KhadasVim3 support

### ISSUE THREAD

**Issue by raghavzns** [Qengineering/PaddleOCR-Lite-License#1]
Hi Sir,
I have two queries :-

1. Can you specify the video file you used for RPI5, i mean was it 720p or 1080p ?
2. Can you please help/guide with using the RPI5 GPU so as to further increase the fps ? Is it possible to use NPU/GPU of SOC's to increase the fps ?

**Comment by Qengineering** [comment]
1) The used video is 1284 x 756.
2) Using the RPi GPU for deep learning tasks is real nightmare. Don't walk that path.
3) Yes NPUs can accelerate you throughput. At the moment I'm using the Radxa Zero 3W - 4GB RAM - ± $30,=. The NPU supports Paddle OCR (See the Rockchip model zoo). Buy only the 4 GB, lower numbers don't support the NPU well.
Other possible RPi5 alternatives are the Rock 5 or Orange Pi 5. All have the Rockchip NPU and are much cheaper than the VIM3.
